---
name: unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
    with:
      activate-environment: hw5
      environment-file: ../../environment.yml
    run: |
      cd ../test/unit
      python test_my_utils.py
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
    with:
      activate-environment: hw5
      environment-file: ../../environment.yml
    run: |
      cd ../test/func
      python test_print_fires.py
