name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test_installations:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: hw6
      - run: |
          conda list matplotlib
          conda list pycodestyle
          micromamba list matplotlib
          
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: hw6
      - run: |
          cd test/unit
          python test_my_utils.py
          
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: hw6
      - run: |
          cd test/func
          bash test_print_fires.sh

  run_style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: hw6
      - run: |
          cd src
          pycodestyle my_utils.py
          pycodestyle print_fires.py